name: windows
on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  windows_openssl:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - run: |
        vcpkg install zlib:x64-windows
        vcpkg install openssl:x64-windows
    - run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=cl.exe -DUSE_OPEN_SSL=1 -DUSE_TLS=1 -DCMAKE_BUILD_TYPE=Release ..
    - run: cmake --build build
    - uses: actions/upload-artifact@v2
      with:
        name: ixwebsocket-release
        path: ./Release/